import { startOfToday, addDays, getTime } from "date-fns";

const today = startOfToday();

const sampleData = [
  {
    title: "Get quotation",
    notes: "Contact dealer by phone",
    dueDate: getTime(today),
    priority: 2,
    project: "Inbox",
    isDone: false,
  },
  {
    title: "Get milk",
    notes: "from the supermarket",
    dueDate: getTime(addDays(today, 1)),
    priority: 2,
    project: "Inbox",
    isDone: true,
  },
  {
    title: "Go to library",
    notes: "Return the book",
    dueDate: null,
    priority: 2,
    project: "Inbox",
    isDone: false,
  },
  {
    title: "Implement Ship Class",
    notes: "Create properties for length, hits, and sunk status",
    dueDate: getTime(addDays(today, 1)),
    priority: 2,
    project: "Battleship Game",
    isDone: true,
  },
  {
    title: "Gameboard Logic",
    notes: "Write function to place ships at specific coordinates",
    dueDate: null,
    priority: 2,
    project: "Battleship Game",
    isDone: false,
  },
  {
    title: "Attack Functionality",
    notes: "Handle missed shots and successful hits",
    dueDate: getTime(addDays(today, 10)),
    priority: 1,
    project: "Battleship Game",
    isDone: true,
  },
  {
    title: "Check Game Over",
    notes: "Verify if all ships on board are sunk",
    dueDate: null,
    priority: 0,
    project: "Battleship Game",
    isDone: false,
  },
  {
    title: "Bencode Parser",
    notes: "Implement decoding for integers and strings",
    dueDate: getTime(today),
    priority: 2,
    project: "BitTorrent Client",
    isDone: true,
  },
  {
    title: "UDP Tracker Request",
    notes: "Send connect message and handle response",
    dueDate: getTime(addDays(today, 14)),
    priority: 2,
    project: "BitTorrent Client",
    isDone: false,
  },
  {
    title: "Peer Handshake",
    notes: "Establish TCP connection with a peer",
    dueDate: getTime(addDays(today, 35)),
    priority: 1,
    project: "BitTorrent Client",
    isDone: false,
  },
  {
    title: "Piece Verification",
    notes: "Validate SHA1 hashes for downloaded blocks",
    dueDate: getTime(addDays(today, -2)),
    priority: 1,
    project: "BitTorrent Client",
    isDone: true,
  },

  {
    title: "Webpack Dev Server",
    notes: "Configure hot module replacement",
    dueDate: getTime(today),
    priority: 1,
    project: "Development Workflow",
    isDone: true,
  },
  {
    title: "Neovim LSP Config",
    notes: "Add completion for JavaScript and CSS",
    dueDate: getTime(addDays(today, -3)),
    priority: 2,
    project: "Development Workflow",
    isDone: false,
  },
  {
    title: "Git Ignore Setup",
    notes: "Exclude node_modules and build folders",
    dueDate: null,
    priority: 0,
    project: "Development Workflow",
    isDone: true,
  },
  {
    title: "Typst Resume Template",
    notes: "Structure contact info and work history",
    dueDate: getTime(addDays(today, 20)),
    priority: 1,
    project: "Development Workflow",
    isDone: false,
  },
  {
    title: "Book Constructor",
    notes: "Define title, author, and pages",
    dueDate: getTime(addDays(today, 14)),
    priority: 1,
    project: "Library System",
    isDone: true,
  },
  {
    title: "Local Storage Sync",
    notes: "Save library array to browser storage",
    dueDate: getTime(addDays(today, 8)),
    priority: 2,
    project: "Library System",
    isDone: false,
  },
  {
    title: "Read Status Toggle",
    notes: "Function to change 'read' boolean on prototype",
    dueDate: getTime(addDays(today, 65)),
    priority: 0,
    project: "Library System",
    isDone: true,
  },
  {
    title: "Search Filter",
    notes: "Filter books by author or title string",
    dueDate: getTime(addDays(today, 84)),
    priority: 1,
    project: "Library System",
    isDone: false,
  },

  {
    title: "Win Condition Logic",
    notes: "Check rows, columns, and diagonals",
    dueDate: getTime(today),
    priority: 2,
    project: "Tic-Tac-Toe",
    isDone: true,
  },
  {
    title: "Display Controller",
    notes: "Render board array to the DOM",
    dueDate: getTime(addDays(today, 1)),
    priority: 2,
    project: "Tic-Tac-Toe",
    isDone: true,
  },
  {
    title: "CPU Move AI",
    notes: "Implement a simple random move generator",
    dueDate: getTime(addDays(today, 3)),
    priority: 0,
    project: "Tic-Tac-Toe",
    isDone: false,
  },
  {
    title: "Reset Button",
    notes: "Clear board state and update UI",
    dueDate: getTime(addDays(today, 370)),
    priority: 1,
    project: "Tic-Tac-Toe",
    isDone: false,
  },
];

export default sampleData;
